### ISSUE TITLE
移动web开发问题

### ISSUE THREAD

**Issue by lenqwang** [qqcome110/web#10]
### 解决移动浏览器滑动出界问题

``` css
body {
    -webkit-overflow-scrolling: touch;
}

.el {
    overflow: scroll;
}
```

``` javascript
/*
 scrollFix
*/
var ScrollFix = function(elem) {
    // Variables to track inputs
    var startY, startTopScroll;

    elem = elem || document.querySelector(elem);

    // If there is no element, then do nothing  
    if(!elem)
        return;

    // Handle the start of interactions
    elem.addEventListener('touchstart', function(event){
        startY = event.touches[0].pageY;
        startTopScroll = elem.scrollTop;

        if(startTopScroll <= 0)
            elem.scrollTop = 1;

        if(startTopScroll + elem.offsetHeight >= elem.scrollHeight)
            elem.scrollTop = elem.scrollHeight - elem.offsetHeight - 1;
    }, false);
};
```
